UnitexGramLab/unitex-core

Cassys.cpp
Cassys.h
Cassys_concord.cpp
Cassys_concord.h

New argument **istex** has been added. Depending upon the value of this argument CasSys will output in xml format either a token list or a standoff file.

New output files for CasSys

---

Cassys.cpp

generic graph should look at all annotations and not just innermost.

Fix error in generic graph

---

Cassys_concord.cpp

unreferenced formal parameter
signed/unsigned mismatch

Fix compilation warnings

---

Cassys.cpp
Cassys_concord.cpp

entity count will also be stored in the standoff file

frequencies for standoff

---

Cassys.cpp
Cassys.h
Cassys_concord.cpp
Cassys_concord.h

change parameter from istex to standoff
pass lang parameter to be printed in the standoff file

standoff language

---

Cassys.cpp
Cassys.h
Cassys_concord.cpp
Cassys_concord.h

Cassys can be passed an optional header file. If the file is present it
is appended before the standoff file.

Header for standoff

---

Cassys_concord.cpp

Format of frequency is changed from
<numeric>n</numeric>
to
<numeric valiue=’n’/>

[fix] Change istex output

---

Cassys_concord.cpp

Delete xmsl=‘https://tei-c.org/ns/1.0' from annotationBlock
Add s to http and replace lod by data in ‘scheme’ attribute

[minor enhance] Update standoff output

---

VersionInfo.cpp

Reverts UnitexGramLab/unitex-core#32

Revert "Changes to CasSys and VersionInfo"

---

VersionInfo.cpp

New feature added in VersionInfo to show build date in YYYY-MM-DD
format

[minor feature] Add display build date

---

Cassys_concord.cpp

Instead of hardcoding the xml structure in the code, it is read from a
file and populated with values obtained from concord.ind.

[minor enhance] Change standoff file generation

---

Grf2Fst2_lib.cpp
Grf2Fst2_lib.h
Grf_lib.cpp
Grf_lib.h

Removing the feature introduced with a803b2e and 777a3e1:
user can add output to a box with subgraph.

[minor remove] Revert subgraph output

---

Cassys.cpp

Previously graph generalisation could detect word forms in nested
annotations of depth 2. This constraint has been removed.

[minor fix] Graph Generalisation supports multiple levels of annotation

---

Cassys.cpp
Cassys_transducer.cpp
Cassys_transducer.h

rename constant to avoid collision

---

PackInf.cpp
PackInf.h
build/Android.mk
build/UnitexLibAndJni.vcxproj
build/UnitexLibAndJni.vcxproj.filters
build/UnitexLibAndJni.xcodeproj/project.pbxproj
build/UnitexLibAndJni_vs2015.vcxproj
build/UnitexLibAndJni_vs2015.vcxproj.filters
build/UnitexLibrary.vcproj
build/UnitexLibrary.vcxproj
build/UnitexLibrary.vcxproj.filters
build/UnitexTool.vcproj
build/UnitexTool.vcxproj
build/UnitexTool.vcxproj.filters
build/UnitexTool.xcodeproj/project.pbxproj
build/UnitexToolLogger.vcproj
build/UnitexToolLogger.vcxproj
build/UnitexToolLogger.vcxproj.filters
build/UnitexToolLogger.xcodeproj/project.pbxproj

fix on project for binarize graphs and dictionary codes

---

DictionaryTree.cpp
DutchCompounds.cpp
GeneralDerivation.cpp
NorwegianCompounds.cpp
PackInf.cpp
PackInf.h
build/Android.mk
build/Makefile
build/UnitexLibAndJni.vcxproj
build/UnitexLibAndJni.vcxproj.filters
build/UnitexLibAndJni.xcodeproj/project.pbxproj
build/UnitexLibAndJni_vs2015.vcxproj
build/UnitexLibAndJni_vs2015.vcxproj.filters
build/UnitexLibrary.vcproj
build/UnitexLibrary.vcxproj
build/UnitexLibrary.vcxproj.filters
build/UnitexTool.vcproj
build/UnitexTool.vcxproj
build/UnitexTool.vcxproj.filters
build/UnitexTool.xcodeproj/project.pbxproj
build/UnitexToolLogger.vcproj
build/UnitexToolLogger.vcxproj
build/UnitexToolLogger.vcxproj.filters
build/UnitexToolLogger.xcodeproj/project.pbxproj

rename some structure to avoid lto link warning, makefile fix for JDK>=10

---

AbstractFst2Load.cpp
AbstractFst2Load.h
Flatten.cpp
Fst2.cpp
Grf2Fst2.cpp
PackFst2.cpp

Flatten produce packed FST2 file when read packed FST2

---

Cassys.cpp
Cassys_concord.cpp

Fix cassys concord

---

Cassys.cpp

[Fix] warning cassys

---

Unicode.cpp

[Fix] warning unicode.cpp under MS Visual Studio 2017

---

Fst2List.cpp

Small refactor of Fst2List, adding few comments and renaming variables for clarity.

[minor refactor] rename variables and add comments

---

Fst2List.cpp

tp and ep are renamed, in continuation of Kalkhas'refactoring, see PR #79 
tp and ep are badly named

[minor refactor] Rename tp and ep variables

---

Cassys.cpp

[fix] Solve issue dealing with <masks> on CasSys generic graphs

---

build/UnitexLibAndJni_vs2019.vcxproj
build/UnitexLibAndJni_vs2019.vcxproj.filters
build/UnitexLibrary_vs2019.vcxproj
build/UnitexLibrary_vs2019.vcxproj.filters
build/UnitexToolAndLib_vs2019.sln
build/UnitexToolLogger_vs2019.vcxproj
build/UnitexToolLogger_vs2019.vcxproj.filters
build/UnitexTool_vs2019.vcxproj
build/UnitexTool_vs2019.vcxproj.filters

Adding Visual studio 2019 projects file

add Visual studio 2019 projects

---

UnitexTool.cpp
logger/UniRunScript.cpp
logger/UniRunScript.h

New version of UniRunScript with file result option

---

Concordance.cpp

warning fix for visual studio 2019 - 32 bits x86

warning fix

---

Alphabet.h
Fst2List.cpp
Korean.cpp

Solve the issue #87.
Without this change, the output file of explore graph paths is not readable for Korean users.
This change has been tested on some graphs in korean.
[korean_tests_graphs.zip](https://github.com/UnitexGramLab/unitex-core/files/3371979/korean_tests_graphs.zip)

[enhance] Process korean in explore graph paths

---

Grf2Fst2_lib.cpp

[fix] Fix crash on Grf2Fst2 with specific graph error

[fix] Fix crash on Grf2Fst2 with specific graph error

---

Unxmlize.cpp
Ustring.h
Xml.cpp
Xml.h

[minor enhance] Add option to load xpath from file for Unxmlize

---

Unxmlize.cpp

- add selxpath_file in usage
- fix selxpath (without _file)

[fix] Fix on new Unxmlize selxpath:

---

Concordance.cpp

avoid some test on concordance

[enhance] Minor optimization

---

src/build/Makefile

Resolve syntax error in Makefile
Add missing parenthesis around variable BIN_DIR when it is used.
[issue #122](https://github.com/UnitexGramLab/unitex-core/issues/122) - Error when trying to compile Unitex as a library
This was tested by compiling Unitex as a library with the following command `make 64BITS=yes LIBRARY=yes TRE_DIRECT_COMPILE=yes`
- [ ] `refactor`: Improve coding style, comments

[fix #122] Fix syntax error in Makefile

---

src/base/compiler/version.h
src/base/os/version.h
src/base/vendor/whereami/whereami.c

- [ ] `refactor`: Improve coding style, comments

[minor enhance] Add macros to identify the Emscripten compiler

---

src/ELG_API.h

- [ ] `refactor`: Improve coding style, comments

[fix elg] Resolve tautological bitwise 'or' on uVariable.set

---

src/File.cpp

[fix] Prevent overflow when removing a filaname path and extension 
